---
version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - containers/forward-proxy
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
