# Build forward-proxy image and store in Artifact Registry or
# Container Registry.
---
steps:
  - id: forward-proxy
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile
      - --tag
      - "${_CONTAINER_REPO}/forward-proxy:latest"
      - --tag
      - "${_CONTAINER_REPO}/forward-proxy:${TAG_NAME}"
      - .
    dir: $_WORKING_DIR
images:
  - ${_CONTAINER_REPO}/forward-proxy:latest
  - ${_CONTAINER_REPO}/forward-proxy:${TAG_NAME}
substitutions:
  _CONTAINER_REPO: ''
  _WORKING_DIR: ''
