# Build private-bastion-forward-proxy image and store in Artifact Registry or
# Container Registry.
---
steps:
  - id: private-bastion-forward-proxy
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile
      - --build-arg
      - "COMMIT_SHA=${COMMIT_SHA}"
      - --build-arg
      - "TAG_NAME=${TAG_NAME}"
      - --tag
      - "${_CONTAINER_REPO}/private-bastion-forward-proxy:latest"
      - --tag
      - "${_CONTAINER_REPO}/private-bastion-forward-proxy:${TAG_NAME}"
      - .
    dir: private-bastion-forward-proxy
images:
  - ${_CONTAINER_REPO}/private-bastion-forward-proxy:latest
  - ${_CONTAINER_REPO}/private-bastion-forward-proxy:${TAG_NAME}
substitutions:
  _CONTAINER_REPO: ''
