# yamllint disable rule:line-length rule:new-line-at-end-of-file
---
name: release

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            memes/forward-proxy
            ghcr.io/${{ github.repository }}/forward-proxy
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            maintainer=memes@matthewemes.com
            org.opencontainers.image.title=forward-proxy
            org.opencontainers.image.description=Forward-proxy container for use in private bastion
            org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/containers/forward-proxy/
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/containers/forward-proxy/README.md
      - uses: docker/build-push-action@v2
        with:
          context: ./containers/forward-proxy
          file: ./containers/forward-proxy/Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
