# yamllint disable rule:line-length rule:new-line-at-end-of-file
---
name: release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release_please
        uses: GoogleCloudPlatform/release-please-action@v4.0.0
        with:
          release-type: terraform-module
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release_please.outputs.release_created }}
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ steps.release_please.outputs.release_created }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ steps.release_please.outputs.release_created }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ steps.release_please.outputs.release_created }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        if: ${{ steps.release_please.outputs.release_created }}
        with:
          images: |
            memes/forward-proxy
            ghcr.io/${{ github.repository }}/forward-proxy
          tags: |
            type=semver,pattern={{version}},value=${{ steps.release_please.outputs.tag_name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.release_please.outputs.tag_name }}
          labels: |
            maintainer=memes@matthewemes.com
            org.opencontainers.image.title=forward-proxy
            org.opencontainers.image.description=Forward-proxy container for use in private bastion
            org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/containers/forward-proxy/
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/tree/${{ github.sha }}/containers/forward-proxy/README.md
      - uses: docker/build-push-action@v5
        if: ${{ steps.release_please.outputs.release_created }}
        with:
          context: ./containers/forward-proxy
          file: ./containers/forward-proxy/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
